version: '3'

services:
  apps:
    container_name: apps
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:docker
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - apps-network

networks:
  apps-network:
    # driver: bridge